### ISSUE TITLE
Diagram canvas does not cover full area

### ISSUE THREAD

**Issue by Nick-Russell** [mucs420f19/JJARS#138] opened 2019-12-01 01:40 UTC
Branch feat/custom-dialogs, merge request #134:

On Windows, the diagram canvas does not extend down to the toolbar, leaving a blank white area as seen below.

![image](https://user-images.githubusercontent.com/34797249/69908118-2048c300-13b1-11ea-8d16-7b09142135f0.png)

**Comment by jessiehildebrandt** [comment] 2019-12-01 08:39
Preliminary investigation into the issue suggests that this is caused by Edge calculating flex element sizes differently from other browsers. Am looking into a CSS tweak that might fix this so that we can merge the branch.

**Comment by jessiehildebrandt** [comment] 2019-12-02 10:07
Fixed in [ad4701a](https://github.com/mucs420f19/JJARS/commit/ad4701a6a90c021e53a2879e9fde91bb70af8fe7), will be merged into develop with #134.

**Closed by jessiehildebrandt** 2019-12-02 10:07 UTC
Labels: bug, gui
